ALTER TABLE DW.DATA_VAULT.HUB_ORDER ADD PRIMARY KEY (ORDER_HK);
ALTER TABLE DW.DATA_VAULT.HUB_CUSTOMER ADD PRIMARY KEY (CUSTOMER_HK);

ALTER TABLE DW.DATA_VAULT.LINK_CUSTOMER_ORDER 
ADD FOREIGN KEY(order_hk) 
REFERENCES DW.DATA_VAULT.HUB_ORDER 
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE DW.DATA_VAULT.LINK_CUSTOMER_ORDER 
ADD FOREIGN KEY(customer_hk) 
REFERENCES DW.DATA_VAULT.HUB_CUSTOMER 
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE DW.DATA_VAULT.SAT_CUSTOMER_DETAIL 
ADD FOREIGN KEY(customer_hk) 
REFERENCES DW.DATA_VAULT.HUB_CUSTOMER 
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE dw.data_vault.sat_order_details 
ADD FOREIGN KEY(order_hk) 
REFERENCES dw.data_vault.hub_order 
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE DW.DATA_VAULT.T_LINK_TRANSACTION 
ADD FOREIGN KEY(order_hk) 
REFERENCES DW.DATA_VAULT.HUB_ORDER
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE DW.DATA_VAULT.T_LINK_TRANSACTION 
ADD FOREIGN KEY(customer_hk) 
REFERENCES DW.DATA_VAULT.HUB_CUSTOMER 
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE DW.DATA_VAULT.EFF_SAT_CUSTOMER_NATION 
ADD FOREIGN KEY(customer_hk) 
REFERENCES DW.DATA_VAULT.HUB_CUSTOMER 
MATCH FULL 
ON UPDATE NO ACTION 
ON DELETE NO ACTION;