name: 'dbt_datavault'
version: '5.0.0'
# require-dbt-version: ['>=0.18.0', '<0.19.0']
config-version: 2

profile: 'dbt_datavault'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  load_date: '1992-01-08'
  tpch_size: 10 #1, 10, 100, 1000, 10000


models:
  dbt_datavault:
    raw_stage:
      tags:
        - 'raw'
      +materialized: view
